packages:
  - packages/*

minimumReleaseAgeExclude:
  - typebox
  - vite

overrides:
  vite: 8.2.2

allowBuilds:
  "@google/genai": false
  bufferutil: false
  esbuild: true
  protobufjs: false
  utf-8-validate: false

patchedDependencies:
  micro-key-producer@0.10.2: patches/micro-key-producer@0.10.2.patch
